jobs:
  - job: website
    displayName: Build Website
    pool:
      vmImage: Ubuntu-16.04
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    steps:
      - task: NodeTool@0
        displayName: Install Node.js
        inputs:
          versionSpec: 14.x

      - script: npm install
        displayName: Install Packages

      - script: npm run -s docs:build
        displayName: Build Website

      - script: npm run -s docs:deploy -- $(GH_TOKEN)
        displayName: Deploy
        condition: succeeded()
