name: CI
on:
  push:
    branches: [main, gha]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with: { node-version: 14.x }
      - name: Install Packages
        run: npm install
      - name: Lint
        run: npm run -s lint

  test:
    name: Test
    strategy:
      matrix:
        eslint: [7.x]
        node: [14.x]
        os: [ubuntu-latest]
        include:
          # On other platforms
          - eslint: 7.x
            node: 14.x
            os: windows-latest
          - eslint: 7.x
            node: 14.x
            os: macos-latest
          # On old Node.js versions
          - eslint: 7.x
            node: 12.x
            os: ubuntu-latest
          - eslint: 7.x
            node: 10.x
            os: ubuntu-latest
          - eslint: 6.x
            node: 8.x
            os: ubuntu-latest
          - eslint: 5.x
            node: 6.x
            os: ubuntu-latest
          # On the minimum supported ESLint/Node.js version
          - eslint: "4.19.1"
            node: "6.5.0"
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with: { node-version: "${{ matrix.node }}" }
      - name: Install npm 6.x
        run: npm install --global npm@6.x
        if: ${{ matrix.node == '6.x' || matrix.node == '6.5.0' }}
      - name: Install Packages
        run: npm install
      - name: Install ESLint ${{ matrix.eslint }}
        run: npm install --no-save eslint@${{ matrix.eslint }}
      - name: Test
        run: npm run -s test:ci
      - name: Send Coverage
        run: npm run -s codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
